// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7YFfxA0-8k-6i2iJVp29YXmmPdgp6fc',
    appId: '1:506087141855:web:47faa518459db81d75546a',
    messagingSenderId: '506087141855',
    projectId: 'questify-af45e',
    authDomain: 'questify-af45e.firebaseapp.com',
    storageBucket: 'questify-af45e.firebasestorage.app',
    measurementId: 'G-QXFK82JZF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChWDuMGyiIN8IIzFE1-eJr-CLGpZySmlk',
    appId: '1:506087141855:android:852181686d897ad675546a',
    messagingSenderId: '506087141855',
    projectId: 'questify-af45e',
    storageBucket: 'questify-af45e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6klSrVX-KrgGl8Iwz9wVVvaiBT8Fd6I',
    appId: '1:506087141855:ios:7f875858b3a8cd1b75546a',
    messagingSenderId: '506087141855',
    projectId: 'questify-af45e',
    storageBucket: 'questify-af45e.firebasestorage.app',
    iosBundleId: 'com.questify.app',
  );

}